<?php

namespace App;

use App\Scopes\LoggedUser;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Expense extends Model
{
    use SoftDeletes;
    
    protected $guarded = [ 'id' ];
    protected $dates   = [ 'created_at', 'updated_at', 'deleted_at', 'date' ];
    
    
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    
        static::addGlobalScope( new LoggedUser() );
    }
    
    public function user()
    {
        return $this->belongsTo( User::class );
    }
}
