<?php

namespace App;

use App\Scopes\LoggedUser;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Income extends Model
{
    use SoftDeletes;

    protected $primaryKey   = 'uuid';
    protected $keyType      = 'string';
    public    $incrementing = false;

    protected $guarded = [ 'id', 'uuid' ];
    protected $dates   = [ 'created_at', 'updated_at', 'deleted_at', 'date' ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope( new LoggedUser() );
    }
}
