<?php

namespace App;

use App\Scopes\LoggedUser;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Reports extends Model
{
    protected $table = 'incomes_expenses';
    
    protected $dates = [ 'updated_at', 'date' ];
    
    
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    
        static::addGlobalScope( new LoggedUser() );
    }
    
    public static function getMonthlyMealReaport( $request )
    {
        if ( $request->s ) {
            $reports = new Meal();
            $reports->select( DB::raw( 'user_id', 'date', 'sum(total)' ) );
            if ( $request->year ) {
                $reports = $reports->where( DB::raw( 'year(date)' ), $request->year );
            }
            if ( $request->month ) {
                $reports = $reports->where( DB::raw( 'month(date)' ), $request->month );
            }
            $reports = $reports->groupBy( "date", 'user_id' )->orderBy( "date" )->get();
            
            $data = [];
            
            
            foreach ( $reports as $report ) {
                $data[$report->user_id]['user']      = $report->user->name;
                $data[$report->user_id]['reports'][] = $report->toArray();

//                $report->user_id

//                $data['user'][$report->user_id]     = $report->user->name;
//                $data[]['report'][$report->user_id] = $report->toArray();
            }
            
            return $data;
        }
        
        return FALSE;
    }
}
